# Generated by Django 3.2.7 on 2021-09-02 13:28

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', froala_editor.fields.FroalaField()),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='blog')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('upload_to', models.DateField(auto_now=True)),
            ],
        ),
    ]
